name: Puppeteer Docker Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROD_ENV: ${{ secrets.PROD_ENV }}
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create .env
        run: echo '${{ env.PROD_ENV }}' > .env

      # Set up Docker Buildx (optional, for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (if pushing images to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/webscreenshoter:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/webscreenshoter:latest
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          port: ${{secrets.DROPLET_PORT}}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/webscreenshoter:latest
            docker stop webscreenshoter || true
            docker rm webscreenshoter || true
            docker run --add-host host.docker.internal:host-gateway --network n8n_redis_net -d --name webscreenshoter -p 1338:1338 ${{ secrets.DOCKER_USERNAME }}/webscreenshoter:latest
